import type { ReviewPresetId, ViewerUiState } from './modelSchema'

export interface ReviewPreset {
  id: ReviewPresetId
  name: string
  description: string
  apply: () => Partial<ViewerUiState> & {
    visibleLayerIds?: string[]
    cameraView?: 'front' | 'side' | 'top' | 'iso' | 'reset'
  }
}

const FACADE = ['frame', 'doorFrame', 'door', 'outletFront', 'grilleBottom']
const CLEAN = [
  'shell',
  'grilleBottom',
  'cleanFan',
  'outletFront',
  'outletSide',
  'hoodSeal',
  'frame',
  'flue',
]
const COMBUSTION_LAYERS = [
  'chamber',
  'lining',
  'doorFrame',
  'door',
  'plenum',
  'primary',
  'secondary',
  'secDistributor',
  'curtain',
  'exteriorIntake',
  'baffle',
]

export const REVIEW_PRESETS: ReviewPreset[] = [
  {
    id: 'layersDidactic',
    name: 'Capas didácticas',
    description:
      'Chimenea ghost, carcasa semitransparente y cámara opaca para ver el sándwich de envolventes.',
    apply: () => ({
      reviewMode: 'layersDidactic',
      fireplaceVisibility: 'ghost',
      showFlows: false,
      showLabels: false,
      showEnvelopeLabels: true,
      showEnvelopeEdges: true,
      explode: 0,
      envelopeSeparate: 0.35,
      masonryOpacity: 0.2,
      shellOpacity: 0.38,
      chamberOpacity: 1,
      clipEnabled: false,
      doorOpen: false,
      cameraView: 'side',
      visibleLayerIds: ['masonry', 'shell', 'chamber'],
    }),
  },
  {
    id: 'masonryAsShell',
    name: 'Obra = carcasa',
    description:
      'Variante conceptual: sin camisa metálica; el hueco obra–cámara hace de envolvente de aire limpio. Requiere sellado de hueco (no es diseño certificado).',
    apply: () => ({
      reviewMode: 'masonryAsShell',
      fireplaceVisibility: 'ghost',
      showFlows: true,
      activeCircuits: ['heating'],
      showLabels: false,
      showEnvelopeLabels: true,
      showEnvelopeEdges: true,
      explode: 0,
      envelopeSeparate: 0.2,
      masonryOpacity: 0.28,
      shellOpacity: 0.2,
      chamberOpacity: 1,
      clipEnabled: false,
      doorOpen: false,
      cameraView: 'side',
      visibleLayerIds: [
        'masonry',
        'chamber',
        'lining',
        'frame',
        'doorFrame',
        'door',
        'outletFront',
        'grilleBottom',
        'cleanFan',
        'hoodSeal',
        'flue',
      ],
    }),
  },
  {
    id: 'frontClean',
    name: 'Vista frontal',
    description: 'Fachada limpia: rejillas, puerta y marco.',
    apply: () => ({
      reviewMode: 'frontClean',
      fireplaceVisibility: 'ghost',
      showFlows: false,
      showLabels: true,
      showEnvelopeLabels: false,
      explode: 0,
      envelopeSeparate: 0,
      clipEnabled: false,
      doorOpen: false,
      shellOpacity: 0.35,
      chamberOpacity: 1,
      masonryOpacity: 0.2,
      cameraView: 'front',
      visibleLayerIds: [...FACADE, 'shell', 'chamber'],
    }),
  },
  {
    id: 'frontCut',
    name: 'Corte frontal',
    description: 'Corte mostrando puerta, cámara y ventilador.',
    apply: () => ({
      reviewMode: 'frontCut',
      fireplaceVisibility: 'hidden',
      showFlows: true,
      activeCircuits: ['heating', 'combustion'],
      showLabels: true,
      explode: 0,
      clipEnabled: true,
      clipAxis: 'x',
      clipPosition: 0.15,
      doorOpen: false,
      cameraView: 'front',
      visibleLayerIds: [
        'chamber',
        'doorFrame',
        'door',
        'cleanFan',
        'grilleBottom',
        'outletFront',
        'shell',
        'plenum',
      ],
    }),
  },
  {
    id: 'sideCut',
    name: 'Corte lateral',
    description: 'Perfil con los tres recorridos.',
    apply: () => ({
      reviewMode: 'sideCut',
      fireplaceVisibility: 'ghost',
      showFlows: true,
      activeCircuits: 'all',
      showLabels: true,
      explode: 0,
      clipEnabled: true,
      clipAxis: 'x',
      clipPosition: 0,
      cameraView: 'side',
      visibleLayerIds: [
        'masonry',
        'shell',
        'chamber',
        'door',
        'doorFrame',
        'cleanFan',
        'plenum',
        'secondary',
        'baffle',
        'exchanger',
        'flue',
        'outletFront',
        'grilleBottom',
      ],
    }),
  },
  {
    id: 'facadeOnly',
    name: 'Solo fachada',
    description: 'Marco exterior, rejillas y puerta (sin campana de garganta).',
    apply: () => ({
      reviewMode: 'facadeOnly',
      fireplaceVisibility: 'hidden',
      showFlows: false,
      showLabels: true,
      explode: 0,
      doorOpen: false,
      cameraView: 'front',
      visibleLayerIds: FACADE,
    }),
  },
  {
    id: 'cleanAirOnly',
    name: 'Solo aire limpio',
    description: 'Circuito de calefacción: rejillas, ventilador y camisa.',
    apply: () => ({
      reviewMode: 'cleanAirOnly',
      fireplaceVisibility: 'hidden',
      showFlows: true,
      activeCircuits: ['heating'],
      showLabels: true,
      explode: 0.05,
      shellOpacity: 0.4,
      cameraView: 'iso',
      visibleLayerIds: CLEAN,
    }),
  },
  {
    id: 'combustionOnly',
    name: 'Solo combustión',
    description: 'Toma exterior, plenum, canales y cortina.',
    apply: () => ({
      reviewMode: 'combustionOnly',
      fireplaceVisibility: 'ghost',
      showFlows: true,
      activeCircuits: ['combustion'],
      showLabels: true,
      explode: 0.1,
      cameraView: 'iso',
      visibleLayerIds: COMBUSTION_LAYERS,
    }),
  },
  {
    id: 'separationCheck',
    name: 'Comprobar separación',
    description: 'Los tres circuitos a la vez para verificar que no se mezclan.',
    apply: () => ({
      reviewMode: 'separationCheck',
      fireplaceVisibility: 'ghost',
      showFlows: true,
      activeCircuits: 'all',
      showLabels: true,
      explode: 0.2,
      shellOpacity: 0.3,
      cameraView: 'iso',
    }),
  },
  {
    id: 'fit',
    name: 'Encaje',
    description: 'Chimenea y silueta del inserto.',
    apply: () => ({
      reviewMode: 'fit',
      fireplaceVisibility: 'ghost',
      showFlows: false,
      showLabels: true,
      explode: 0,
      clipEnabled: false,
      shellOpacity: 0.35,
      cameraView: 'side',
      visibleLayerIds: ['masonry', 'frame', 'shell', 'chamber', 'doorFrame', 'door'],
    }),
  },
  {
    id: 'combustion',
    name: 'Combustión+',
    description: 'Combustión y gases.',
    apply: () => ({
      reviewMode: 'combustion',
      fireplaceVisibility: 'ghost',
      showFlows: true,
      activeCircuits: ['combustion', 'gases'],
      showLabels: true,
      explode: 0.12,
      visibleLayerIds: [...COMBUSTION_LAYERS, 'exchanger', 'flue'],
    }),
  },
  {
    id: 'exchange',
    name: 'Intercambio',
    description: 'Postcombustión e intercambiador.',
    apply: () => ({
      reviewMode: 'exchange',
      fireplaceVisibility: 'hidden',
      showFlows: true,
      activeCircuits: ['gases', 'heating'],
      showLabels: true,
      explode: 0.15,
      shellOpacity: 0.3,
      visibleLayerIds: ['chamber', 'baffle', 'exchanger', 'flue', 'shell', 'cleanFan', 'outletFront'],
    }),
  },
  {
    id: 'convection',
    name: 'Convección',
    description: 'Camisa, ventilador y salidas.',
    apply: () => ({
      reviewMode: 'convection',
      fireplaceVisibility: 'hidden',
      showFlows: true,
      activeCircuits: ['heating'],
      showLabels: true,
      explode: 0.08,
      shellOpacity: 0.45,
      visibleLayerIds: CLEAN,
    }),
  },
  {
    id: 'exploded',
    name: 'Explosión',
    description: 'Capas separadas manteniendo relación espacial.',
    apply: () => ({
      reviewMode: 'exploded',
      fireplaceVisibility: 'ghost',
      showFlows: false,
      showLabels: true,
      explode: 0.75,
      shellOpacity: 0.5,
      clipEnabled: false,
      doorOpen: false,
    }),
  },
]
